name: cache python
on: workflow_dispatch

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Gradle packages
        uses: actions/cache@v3
        id: gradle
        with:
  
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
